<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.a_Fd7Re' shared service.

return $this->privates['.service_locator.a_Fd7Re'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'api' => ['services', 'App\\Controller\\ApiRestController', 'getApiRestControllerService.php', true],
], [
    'api' => 'App\\Controller\\ApiRestController',
]);
