<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9TrDa8N' shared service.

return $this->privates['.service_locator.9TrDa8N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\IndexController::index' => ['privates', '.service_locator.a_Fd7Re', 'get_ServiceLocator_AFd7ReService.php', true],
    'App\\Controller\\IndexController::oneWithApi' => ['privates', '.service_locator.a_Fd7Re', 'get_ServiceLocator_AFd7ReService.php', true],
    'App\\Controller\\IndexController:index' => ['privates', '.service_locator.a_Fd7Re', 'get_ServiceLocator_AFd7ReService.php', true],
    'App\\Controller\\IndexController:oneWithApi' => ['privates', '.service_locator.a_Fd7Re', 'get_ServiceLocator_AFd7ReService.php', true],
], [
    'App\\Controller\\IndexController::index' => '?',
    'App\\Controller\\IndexController::oneWithApi' => '?',
    'App\\Controller\\IndexController:index' => '?',
    'App\\Controller\\IndexController:oneWithApi' => '?',
]);
