<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1AvgT0c\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1AvgT0c/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1AvgT0c.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1AvgT0c\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1AvgT0c\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1AvgT0c',
    'container.build_id' => 'b8677734',
    'container.build_time' => 1576250034,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1AvgT0c');
