<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container77T4brB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container77T4brB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container77T4brB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container77T4brB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container77T4brB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '77T4brB',
    'container.build_id' => '128992ad',
    'container.build_time' => 1575971445,
], __DIR__.\DIRECTORY_SEPARATOR.'Container77T4brB');
