<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIvd0HI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIvd0HI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIvd0HI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIvd0HI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXIvd0HI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XIvd0HI',
    'container.build_id' => 'd43adca6',
    'container.build_time' => 1576419151,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIvd0HI');
